version: '3'
services:
  dbt:
    build: .
    volumes:
      - '.:/usr/app/dbt'
    entrypoint:
      - bash
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
