version: '3'
services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-redshift
    volumes:
      - '.:/usr/app/dbt'
    entrypoint:
      - bash
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DBT_USER
      - DBT_PASSWORD
      - DBT_PROFILES_DIR=/usr/app/dbt
