Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9

Resources:
  RedshiftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Redshift ingress
      VpcId: vpc-27ccbb5d 
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 5439
          ToPort: 5439

  RedshiftNamespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      NamespaceName: dart-warehouse
      LogExports:
        - userlog
        - connectionlog
        - useractivitylog

  RedshiftWorkgroup:
    Type: AWS::RedshiftServerless::Workgroup
    Properties:
      WorkgroupName: dart-warehouse-wg
      NamespaceName: !Ref RedshiftNamespace
      PubliclyAccessible: true
      SecurityGroupIds:
        - !Ref RedshiftSecurityGroup
      Tags:
        - Key: RedshiftDataFullAccess
          Value: "true"

  PollVehiclePositions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: poll_dart_functions
      Handler: poll_vehicle_positions.handler
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          DB_NAME: !GetAtt RedshiftNamespace.Namespace.DbName
          ADMIN_USERNAME: !GetAtt RedshiftNamespace.Namespace.AdminUsername
          WORKGROUP_NAME: !Ref RedshiftWorkgroup
      Policies:
        - arn:aws:iam::aws:policy/AmazonRedshiftDataFullAccess
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 minute)"