Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.9

Resources:
  ResourceGroup:
    Type: "AWS::ResourceGroups::Group" 
    Properties:
      Name: !Ref AWS::StackName
      Description: "Resources for the dart_warehouse POC"

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SQL ingress
      VpcId: vpc-27ccbb5d
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  RDSCluster: 
    Type: "AWS::RDS::DBCluster"
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 14.6
      MasterUsername: postgres
      ManageMasterUserPassword: true
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 1
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup

  DBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties: 
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      PubliclyAccessible: true

  # RedshiftNamespace:
  #   Type: AWS::RedshiftServerless::Namespace
  #   Properties:
  #     NamespaceName: dart-warehouse

  # RedshiftWorkgroup:
  #   Type: AWS::RedshiftServerless::Workgroup
  #   Properties:
  #     WorkgroupName: dart-warehouse-wg
  #     NamespaceName: !Ref RedshiftNamespace
  #     PubliclyAccessible: true
  #     BaseCapacity: 32
  #     SecurityGroupIds:
  #       - !Ref RedshiftSecurityGroup
  #     Tags:
  #       - Key: RedshiftDataFullAccess
  #         Value: "true"

  PollVehiclePositions:
    Type: AWS::Serverless::Function
    DependsOn:
      - DBInstance
    Properties:
      CodeUri: poll_dart_functions
      Handler: poll_vehicle_positions.handler
      Layers:
       - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          DATABASE_HOST: !GetAtt RDSCluster.Endpoint.Address
          DATABASE_PORT: !GetAtt RDSCluster.Endpoint.Port
          DATABASE_SECRET_ARN: !GetAtt RDSCluster.MasterUserSecret.SecretArn
      Policies:
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action: "secretsmanager:GetSecretValue"
              Resource: !GetAtt RDSCluster.MasterUserSecret.SecretArn
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 minute)"

Outputs:
  DatabaseAddress:
    Value: !GetAtt RDSCluster.Endpoint.Address
  DatabasePort:
    Value: !GetAtt RDSCluster.Endpoint.Port
  DatabaseSecretArn:
    Value: !GetAtt RDSCluster.MasterUserSecret.SecretArn